production:
  adapter: postgresql
  database: lunchvoting_db
  host: localhost
  username: lunchvoting_u
  password: lunchvoting

development:
  adapter: postgresql
  database: lunchvoting_db
  host: localhost
  username: lunchvoting_u
  password: lunchvoting

test:
  adapter: postgresql
  database: lunchvoting
  host: localhost
  username: lunchvoting_u
  password: lunchvoting